language: node_js
node_js:
  - "10"
os: osx
addons:
  chrome: beta
env:
  - CODECOV_TOKEN="50b05140-c977-496c-a172-d2a53582159a"
script:
  - npm run lint
  - npm run test
  - npm run build
after_success:
  - codecov
